{
	"version": 1604520300,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/fundojogo-sheet0.png",
		"images/fundojogo-sheet1.png",
		"images/fundojogo-sheet2.png",
		"images/menu-sheet0.png",
		"images/menu-sheet1.png",
		"images/titulo-sheet0.png",
		"images/transicao-sheet0.png",
		"images/cutscen1rua-sheet0.png",
		"images/wilsoncurtscene1-sheet0.png",
		"images/wilsoncurtscene1-sheet1.png",
		"images/rochellecutscene1-sheet0.png",
		"images/rochellecutscene1-sheet1.png",
		"images/dialogocutscene1-sheet0.png",
		"images/texto.png",
		"images/chefecafe-sheet0.png",
		"images/chefecafe-sheet1.png",
		"images/teatrocenario-sheet0.png",
		"images/mesa-sheet0.png",
		"images/mesa2-sheet0.png",
		"images/oculos-sheet0.png",
		"images/django-sheet0.png",
		"images/django-sheet1.png",
		"images/dialogocutscene2-sheet0.png",
		"images/tilemap.png",
		"images/tiledbackground.png",
		"images/django2-sheet0.png",
		"images/django2-sheet1.png",
		"images/voidchao-sheet0.png",
		"images/passarfase-sheet0.png",
		"images/printfcoletavel-sheet0.png",
		"images/parentesescoletavel-sheet0.png",
		"images/hellocoletavel-sheet0.png",
		"images/worldcoletavel-sheet0.png",
		"images/vidas-sheet0.png",
		"images/void2-sheet0.png",
		"images/sentencafase1-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"media/musica-menu.ogg",
		"media/musicacutscene1.ogg",
		"media/do it for himher chiptune8 bits - steven universe.ogg",
		"media/moeda.ogg",
		"media/adhesivewombat - night shade.ogg",
		"media/joshua mclean - mountain trial.ogg",
		"media/kevin macleod - 8bit dungeon boss.ogg",
		"media/thnks fr th mmrs.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}